ProductNUM: EAI_SMART_A02_M1129002_TG30
base_type: 0  # CIRCLE = 0 SQUARE = 1
base_radius_mm: 520  # the radius of platform
distance_between_wheels_mm: 365
chassis_pos0_x: 0
chassis_pos0_y: 0
chassis_pos1_x: 0
chassis_pos1_y: 0
chassis_pos2_x: 0
chassis_pos2_y: 0
chassis_pos3_x: 0
chassis_pos3_y: 0
base_snoar_num: 5
base_snoars0_x: -245
base_snoars0_y: -89
base_snoars0_z: 150
base_snoars0_w: 230  # anti clockwise angle to center degree
base_snoars1_x: 167
base_snoars1_y: -200
base_snoars1_z: 150
base_snoars1_w: -310
base_snoars2_x: 260
base_snoars2_y: 0
base_snoars2_z: 150
base_snoars2_w: 0
base_snoars3_x: 167
base_snoars3_y: 200
base_snoars3_z: 150
base_snoars3_w: 50
base_snoars4_x: -245
base_snoars4_y: 89
base_snoars4_z: 150
base_snoars4_w: 130
base_snoars5_x: 0
base_snoars5_y: 0
base_snoars5_z: 0
base_snoars5_w: 0
base_snoars6_x: 0
base_snoars6_y: 0
base_snoars6_z: 0
base_snoars6_w: 0
base_snoars7_x: 0
base_snoars7_y: 0
base_snoars7_z: 0
base_snoars7_w: 0
base_snoars8_x: 0
base_snoars8_y: 0
base_snoars8_z: 0
base_snoars8_w: 0
base_snoars9_x: 0
base_snoars9_y: 0
base_snoars9_z: 0
base_snoars9_w: 0
base_bumper_num: 4
base_bumpers0_x: 126
base_bumpers0_y: -201
base_bumpers0_z: 10
base_bumpers0_w: 302
base_bumpers1_x: 232
base_bumpers1_y: -52
base_bumpers1_z: 10
base_bumpers1_w: 347
base_bumpers2_x: 52
base_bumpers2_y: 232
base_bumpers2_z: 10
base_bumpers2_w: 13
base_bumpers3_x: 201
base_bumpers3_y: 126
base_bumpers3_z: 10
base_bumpers3_w: 58
base_drop_num: 4
base_drops0_x: -214
base_drops0_y: -107
base_drops0_z: 100
base_drops0_w: 207
base_drops1_x: 214
base_drops1_y: -107
base_drops1_z: 100
base_drops1_w: 344
base_drops2_x: 214
base_drops2_y: 107
base_drops2_z: 100
base_drops2_w: 27
base_drops3_x: -214
base_drops3_y: 107
base_drops3_z: 100
base_drops3_w: 164
base_lidar_num: 2
base_lidar0_x: 50
base_lidar0_y: 0
base_lidar0_z: 280
base_lidar0_w: 0
base_lidar1_x: 200
base_lidar1_y: 0
base_lidar1_z: 50
base_lidar1_w: 0
base_camera_x: 0
base_camera_y: 0
base_camera_z: 0
base_camera_w: 0